
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/

# Hass
api_password: csioz74PfrNntki4U3A=
latitude: 40.753900
longitude: -73.938710

# Tokens
telegram_api_key: 420641387:AAG224o_u348wYkylaAT7mshzs1YBard4Qo
darksky_api_key: 87160c75d9281775c599248102733626
google_assistant_api_key: AIzaSyBkyYxSaIFW2AX0jYV1PpRRuKNnM2rZ824
mi_token: 4c5569334e453750586d354a704a3379
ifttt_token: hfAFpMwCdJsTD8pyvViy-rkcIUq1W6pA6qQ-zQ5M9F7

# Passwords
tile_password: 2NV3vpbMNw9KjHP
