- alias: 'Might rain today'
  initial_state: true
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    condition: numeric_state
    entity_id: sensor.rain_precip_probability
    above: 35
  action:
    service: telegram_bot.send_message
    data_template:
      message: "According to my metrics, it might rain today, current probability of precipitation is {{ states('sensor.rain_precip_probability') }}% \nI advise you to take an umbrella with you!"

#- alias: 'Telegram: Turn Lights back on'
#  initial_state: true
#  trigger:
#    platform: event
#    event_type: telegram_callback
#    event_data:
#      data: '/turnOn lights'
#  action:
#    - service: light.turn_on
#      entity_id:
#        - light.sofa_lamp
#        - light.computer_lamp
#    - service: telegram_bot.edit_replymarkup
#      data_template:
#        message_id: '{{ trigger.event.data.message.message_id }}'
#        chat_id: '{{ trigger.event.data.user_id }}'
#        inline_keyboard: []
#    - service: telegram_bot.send_message
#      data_template:
#        message: "My apologies for the confusion. I turned lights back on :)"

- alias: 'Telegram: Dismiss'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/dismiss'
  action:
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        inline_keyboard: []
