esphome:
  name: smart_intercom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

ota:

api:
  reboot_timeout: 0s

switch:
  - platform: gpio
    pin: D1
    id: relay
  - platform: template
    name: "Intercom"
    icon: "mdi:icon-building"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 10000ms
    - switch.turn_off: relay

